version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - ./workflows:/home/node/.n8n/workflows
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
